import {
  Dropdown,
  Main,
  InfoCard_A,
  InfoDisplay,
  Book,
  Overdue_Books,
  Books_Issued,
  Chart,
  Borrowed_Books,
  BooksView,
  SettingsView,
} from "@/components";
import { RootState } from "@/redux/store";
import { books_data, options } from "@/util/aux_data";
import Head from "next/head";
import { FaHourglass, FaUser, FaUsers } from "react-icons/fa";
import { GiBookshelf } from "react-icons/gi";
import { useSelector } from "react-redux";

export default function Home() {
  const dashboardState = useSelector(
    (state: RootState) => state.dashboardSlice
  );
  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-1 min-h-screen p-10 h-fit bg-main-one rounded-xl relative overflow-hidden">
        <div
          className="absolute top-0 right-0 w-full h-full bg-fixed bg-center bg-no-repeat opacity-10 bg-contain"
          style={{ backgroundImage: "url('/img/afit_logo.png')" }}
        ></div>
        <div
          className="flex text-white font-bold z-[10]"
          style={{ fontSize: "calc(1rem + 1vw)" }}
        >
          <h1 className="mr-2">Hello,</h1>
          <div className="flex-1">
            <h1 className="text-red-500">Abdulganiyu</h1>
            <p className="text-[0.8rem] font-light">Admin</p>
          </div>
        </div>

        {dashboardState.view == "default" ? (
          <Dropdown
            isSearchable
            isMulti
            placeHolder="Select..."
            options={options}
            onChange={(value: any) => console.log(value)}
          />
        ) : null}

        {/* NAVIGATION */}
        {dashboardState.view == "default" ||
        dashboardState.view == "Total Visitors" ||
        dashboardState.view == "Borrowed Books" ||
        dashboardState.view == "New Members" ||
        dashboardState.view == "Overdue Books" ? (
          <div className="flex flex-wrap w-full h-fit max-h-[130px] min-h-[10vh] duration-500 z-[200] my-10 relative">
            <InfoCard_A val={1206} Icon={FaUsers} title="Total Visitors" />
            <InfoCard_A val={74} Icon={GiBookshelf} title="Borrowed Books" />
            <InfoCard_A val={22} Icon={FaHourglass} title="Overdue Books" />
            <InfoCard_A val={60} Icon={FaUser} title="New Members" />
          </div>
        ) : null}

        {/* CONTENT */}

        {/* Default View */}
        {dashboardState.view == "default" ? (
          <div
            className="w-full h-fit"
            style={{ animation: "slide_up_fast 1s ease" }}
          >
            <InfoDisplay />

            <h1
              className="text-white font-semibold my-10"
              style={{ fontSize: "calc(1rem + 0.5vw)" }}
            >
              Top Choices
            </h1>

            <div className="flex flex-wrap w-full">
              <Book link="" img="/img/book_cover_four.png" />
              <Book link="" img="/img/book_cover_four.png" />
              <Book link="" img="/img/book_cover_four.png" />
            </div>

            <Overdue_Books book_data={books_data} />
            <Books_Issued book_data={books_data} />

            <Chart />
          </div>
        ) : null}

        {/* Borrowed Books */}
        {dashboardState.view == "Borrowed Books" ? (
          <Borrowed_Books book_data={books_data} />
        ) : null}

        {/* Books View */}
        {dashboardState.view == "Books" ? <BooksView /> : null}

        {/* Settings View */}
        {dashboardState.view == "Settings" ||
        dashboardState.view == "Login & Security" ||
        dashboardState.view == "Notifications" ||
        dashboardState.view == "Interface" ? (
          <SettingsView />
        ) : null}
      </div>
    </Main>
  );
}
